name: graphistry
channels:
  - conda-forge/label/cf201901
dependencies:
  - python=3.7
  - pytest=4.0.1
  - pytest-timeout=1.3.3
  - networkx=2.2
  - requests=2.20.1
  - pandas=0.23.4
  - pyarrow=0.11.1
  - ipykernel=5.1.0
  - python-igraph=0.7.1.post6
  - pip:
    - neo4j==1.7.1
